import { FC } from "react";

export const FrequentlyAskedQuestionsPage: FC = () => (
  <section>
    <h1>FAQ</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean odio tellus, tristique consectetur aliquet luctus, aliquam efficitur lectus. Donec bibendum ullamcorper nunc quis tincidunt. Nam eleifend fringilla arcu consequat vestibulum. Fusce magna velit, luctus vitae elit sit amet, egestas eleifend est. Aenean at rhoncus odio, a gravida ipsum. Quisque consectetur, turpis at cursus cursus, lacus eros aliquet turpis, ac eleifend lacus felis sit amet elit. Nunc in pharetra erat, in tristique tortor. Mauris mollis faucibus ante, sit amet vestibulum nulla varius non. Donec commodo laoreet turpis. Suspendisse commodo dignissim risus, a viverra ex rutrum a.</p>
    <p>Vestibulum accumsan nibh a ex dapibus, tempor semper nulla imperdiet. Donec condimentum neque in consectetur congue. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam congue est nec ligula vehicula, a rhoncus est consequat. Suspendisse potenti. Fusce sed sollicitudin tortor, sed condimentum lectus. Etiam sit amet ex in elit tempor laoreet. Proin in imperdiet turpis. Nullam et tincidunt est, vitae malesuada magna.</p>
    <p>In purus purus, consequat id nisl vel, elementum euismod justo. Aliquam erat volutpat. Ut sodales odio eu arcu pellentesque tincidunt. Curabitur tempor ligula cursus fringilla aliquet. Duis vitae nisl placerat, auctor lorem sit amet, suscipit justo. Aenean pharetra, erat quis mattis porta, nulla purus pellentesque dui, sed vulputate massa mi a purus. Nulla laoreet interdum dui id tempor.</p>
    <p>Quisque interdum urna vel auctor sagittis. Nullam at venenatis urna, in tristique lectus. Mauris nibh ante, lacinia a urna finibus, vehicula convallis arcu. Vestibulum a leo quis ante malesuada pulvinar. Mauris in nisl in elit pulvinar dictum ac at purus. Nullam imperdiet nisl eu sapien auctor, pretium lobortis urna lobortis. Nam libero erat, tristique vel massa in, gravida imperdiet velit. Fusce malesuada posuere elit nec vestibulum. Proin eleifend sollicitudin sem, ut consectetur elit tempus sit amet. Donec porta lorem a nisl faucibus, vel laoreet felis scelerisque.</p>
    <p>Nunc gravida tortor quis sapien ornare cursus. Ut condimentum est nec augue rutrum porttitor. Mauris molestie non odio et luctus. Maecenas arcu magna, facilisis quis pretium sit amet, bibendum ac nunc. Donec iaculis velit lobortis dui tristique interdum. Praesent vitae imperdiet erat, in aliquam tortor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc non massa risus. Maecenas aliquet ullamcorper mi, eget tincidunt enim pulvinar a. Nulla iaculis vel justo eget tincidunt. Mauris finibus sem magna, quis mattis magna mattis quis. Vestibulum porttitor feugiat diam eu tempor. Nam venenatis auctor placerat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean tincidunt enim lacinia eros finibus, in dignissim erat sodales. Morbi maximus arcu non purus iaculis, id auctor erat gravida.</p>
    <p>Fusce maximus blandit ultricies. Aenean in ipsum ipsum. Vestibulum ultrices lacinia augue id laoreet. Etiam sollicitudin purus tortor, ac hendrerit dui luctus quis. Mauris sodales odio non est ornare ullamcorper et id nulla. Praesent vitae gravida elit. Morbi eget molestie mauris. Aenean eu magna semper, imperdiet risus ut, scelerisque erat. Etiam laoreet vehicula sem non luctus. Donec sed erat ipsum. Maecenas interdum ultrices mauris, in euismod enim congue imperdiet. Curabitur finibus neque ac elit lacinia sollicitudin. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin eu consectetur neque. Curabitur facilisis id quam id auctor. Curabitur pretium tortor sit amet ultricies convallis.</p>
    <p>Nulla pellentesque erat arcu, at elementum nulla pellentesque at. Maecenas vestibulum nec risus fringilla varius. Praesent varius lectus a magna congue posuere. Sed vel risus et sapien ornare eleifend. Pellentesque gravida ullamcorper lorem sit amet blandit. Aenean tincidunt efficitur bibendum. Sed at dolor convallis, mollis nibh vel, gravida est. Cras venenatis turpis nec augue lacinia, dignissim mattis libero porttitor. Vivamus eu libero ac mi tempor pharetra. Praesent sit amet sapien vel sem ornare molestie. Maecenas fringilla malesuada condimentum. Praesent mattis sit amet quam a tempus.</p>
    <p>Phasellus pretium orci a nulla aliquam malesuada. Nullam purus tellus, pretium at tristique in, sollicitudin in purus. Sed arcu libero, aliquet vitae augue eget, cursus porttitor velit. Etiam in lacus nec enim rhoncus sagittis. Proin eget lacinia orci, vitae congue magna. Nunc congue eleifend arcu sit amet mattis. Cras orci enim, ultricies et leo quis, vulputate convallis nunc. Suspendisse sed orci vitae nisi vestibulum eleifend. Maecenas fermentum cursus enim et placerat. Ut lobortis tristique fringilla. Donec ut est vel tortor mattis auctor condimentum vel ex. Sed ornare eros at urna mollis venenatis. Maecenas sed mattis elit. Nunc molestie euismod ipsum, sed dapibus sem aliquet et. Etiam eget nibh nec erat blandit mollis quis in velit. Etiam urna lectus, auctor sit amet dapibus in, varius non erat.</p>
    <p>Nam malesuada nunc et lacus pretium feugiat. Nulla facilisi. Mauris venenatis, dui non efficitur sollicitudin, est magna tincidunt purus, eu dictum ligula neque vel neque. Aliquam interdum dolor sed iaculis sollicitudin. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Curabitur eget felis efficitur, pellentesque velit et, eleifend nisi. Vestibulum rutrum pretium tempus. Nulla vitae elementum libero.</p>
    <p>Vivamus odio turpis, eleifend non ipsum sed, aliquam tristique leo. Cras imperdiet accumsan nisi et porttitor. Nam eget dui ac neque tristique viverra. Donec mollis urna eros, nec auctor odio consectetur in. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras at ligula egestas, venenatis nisl at, auctor nunc. Integer ac ex venenatis, dignissim nunc non, vestibulum sem.</p>
  </section>
);

export default FrequentlyAskedQuestionsPage;